---
azs:
- name: z1

networks:
- name: default
  subnets:
  - az: z1
    gateway: 10.244.16.1
    range: 10.244.16.0/24
    static:
    - 10.244.16.2 # vault
    - 10.244.16.3 # concourse
    - 10.244.16.4 # minio

vm_types:
- name: concourse
  network: default

- name: concourse_worker
  cloud_properties: 
    disk: 10000
  network: default

- name: vault-vm
  network: default

- name: minio-vm
  network: default

disk_types:
- name: db
  disk_size: 10240

- name: vault-disk
  disk_size: 10240

- name: minio-disk
  disk_size: 10240

compilation:
  az: z1
  workers: 3
  network: default
